---
   - name: "{{ packageLog }} Enable"
     yum:
       name: "{{ packageName }}"
       state: present
#       update_cache: yes
     when: packageName not in ansible_facts.packages
     tags:
       - install_epel
       - deploy
