---
   - name: "{{ packageLog }} Disable"
     yum:
       name: "{{ packageName }}"
       state: absent

     when: packageName in ansible_facts.packages
     tags:
       - remove_epel
       - erase
